version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTEST_1211Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: SIQA_GITTEST_1211Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GITTEST_1211Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_gittest_1211.integrations:Test_ConnListing
  packages:
  - name: SIQA_GITTEST_1211Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: SIQACloudStreamsTests:connetorOperations
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQACloudStreamsTests:createAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQACloudStreamsTests:retrieveAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQACloudStreamsTests:deleteAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQAJDBCAdapterTests.adapterServices:getData
  packages:
  - name: SIQA_GITTEST_1211Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: GB_1:readGlobalvariable
  packages:
  - name: DADA_GlobalVariable1
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2099
configurationVariables:
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "3306"
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : 9.46.196.248
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : MySQL
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : siqatest
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GITTEST_1211Project.project.siqa_gittest_1211.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : TestDriver
